apiVersion: v1
kind: Secret
metadata:
  name: primerun-service-secret
  labels:
    app: primerun-service
type: Opaque
data:
  # 'primerun' base64 encoded
  SPRING_DATASOURCE_USERNAME: cHJpbWVydW4=
  SPRING_DATASOURCE_PASSWORD: cHJpbWVydW4=
