apiVersion: v1
kind: Service
metadata:
  name: primerun-service
  labels:
    app: primerun-service
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: primerun-service
